### ISSUE TITLE
Spamming console with exceptions

### ISSUE THREAD

**Issue by Jesseman1** [ilyvion/ilyvion-laboratory#1]
Hello, the library/framework mod is spamming constant exceptions in the console log referencing line 39 which is a mod called "Metal Don't Burn (Unofficial 1.4 Patch)" I'm not sure why your library is having this clash but I'd really like to use the colony manager alongside it.

**Comment by ilyvion** [comment]
Was caused by Colony Manager Redux, not this mod.
